name: Java CI with Gradle

on:
  push:
    branches: [ "lab1" ]
  pull_request:
    branches: [ "lab1" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Checkstyle
      working-directory: lab1/lab
      run: ./gradlew checkstyle --no-daemon

    - name: Build with Gradle Wrapper
      working-directory: lab1/lab
      run: ./gradlew build --no-daemon
